build: off

platform:
  - x64

environment:
  matrix:
    - TOXENV: "py27"
      MINICONDA: "C:\\Miniconda27\\python"
    - TOXENV: "py36"
      MINICONDA: "C:\\Miniconda37\\python"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\MinGW\bin;%PATH%
  - cmd: pip install --force-reinstall tox pytest 

test_script:
  - cmd: tox
  - cmd: python --version
  - cmd: py.test --verbose --capture=no --exitfirst tests

notifications:
  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
